config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:create, :destroy]
  get 'signin', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  get 'authentication/new'
  post 'authentication/create'
  get 'about/index'
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show] 
    resources :categories, except: [:edit, :update, :show, :delete]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation :clean_email

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 6..20 }
  validates :password_confirmation, presence: true

  def clean_email 
    if self.email != nil
      self.email = email.strip.downcase
    end
  end

  def self.authenticate_with_credentials(email_address, password)
    #email = email_address.strip.downcase
    #^ this does not pass in the front end
    @user = User.find_by_email(email_address.strip.downcase)
    if @user && @user.authenticate(password) 
      @user
    else
      nil
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  def index
    @categories = Category.all
  end

  def new
    @categories = Category.new
  end

  def create
    @categories = Category.new(category_params)

    if @categories.save
      redirect_to [:admin, :categories], notice: 'Category created!'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  def show
    @products = Product.all
    @categories = Category.all
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"]

  
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  add_flash_types :info, :error, :warning
  helper_method :current_user
  helper_method :logged_in?
  
  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
        
      !current_user.nil?
  end

  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to "/", notice: 'User created!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        # foregin key to link to the product table
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!
    order
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if user = User.authenticate_with_credentials(params[:user][:email], params[:user][:password])
      # Save the user id inside the browser cookie
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:error] = "Please enter a vaild username and password"
      #send back to the login form.
      redirect_to '/signin'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private

    # Only allow a list of trusted parameters through.
    def session_params
      params.require(:user).permit(
      :email,
      :password
    )
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/about/index.html.erb
<br>
<h4>Our Story</h4>

<div>Jungle focuses on enhancing spreading greens and love xoxo. At Jungle brings thoughtfulness and empathy to add some life to home by having more plants at home</div>

app/views/admin/categories/_category.html.erb
<tr>

  <td>
    <%= category.name %>
  </td>
  
</tr>

app/views/admin/categories/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Categories</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', [:new, :admin, :category], class: 'btn btn-info' %>
  </div>

  <br>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Categories</th>
        </tr>
      </thead>
      <tbody>
        <%= render @categories %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Categories', [:admin, :categories], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @categories] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :category %>
          <%= form.text_area :name, class: 'form-control' %>
        </div>
        <br>
        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/dashboard/show.html.erb
<header class="page-header">
    <h1>Admin &raquo; Dashboard</h1>
</header>
<br>
<h4>Total products in store: <%= link_to @products.count, admin_products_path%></h2>
<br>

<h4>Total categories in store: <%= link_to @categories.count, admin_categories_path%></h2>

app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>
  <br>
  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

app/views/authentication/new.html.erb
<br>
<h4>Sign Up For An Account</h4>
<br>
<div class="row">
<div class="col-sm-6 col-sm-offset-1">
  <%= form_for :user, url: authentication_create_path do |form| %>

    <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% @user.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

    <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <br>
    <%= form.submit 'Create Account', class: 'btn btn-primary' %>
  

  <% end %>
  </div>
</div>

app/views/authentication/register.html.erb
<br>
<h4>Sign Up For An Account</h4>
<br>
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">First Name</label>
  <div class="col-sm-10">
  <input type="name" class="form-control" id="exampleFormControlInput1" placeholder="First Name">
  </div>

  <label for="exampleFormControlInput1" class="form-label">Last Name</label>
  <div class="col-sm-10">
  <input type="name" class="form-control" id="exampleFormControlInput1" placeholder="Last Name">
  </div>

  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <div class="col-sm-10">
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>

  <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword">
    </div>

</div>

<button type="button" class="btn btn-primary">Create Account</button>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>

  <% if enhanced_cart.length > 0 %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% enhanced_cart.each do |item| %>
          <%= render 'item', product: item[:product], quantity: item[:quantity].to_i %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            <%= humanized_money_with_symbol cart_subtotal_cents / 100.0 %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= cart_subtotal_cents %>"
          data-name="Jungle"
          data-description="Khurram Virani's Jungle Order"
          data-locale="auto"
          data-email="kvirani@gmail.com"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>

  <% else %>
  <div class="alert alert-danger" role="alert">Your cart is empty. Please select your items at: <%= link_to("Jungle", "/")%></div>
  <% end %>

</section>

app/views/layouts/_top_nav.html.erb
<header class="<%= current_page?(root_path) ? "hero" : "hero small" %>">
  <section class="title">
    <h3>Welcome to</h3>
    <h1>The Jungle</h1>
    <h2>Where you can find any plants!</h2>
  </section>
</header>
<nav class="navbar navbar-expand-lg navbar-dark sticky-nav">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">Jungle</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          > %>
            <%# Categories %>
          <%# </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown"> %>
            <% Category.all.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category, class: "nav-link" %>
            </li>
            <% end %>
          <%# </ul>
        </li> %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-danger"
            href="#"
            id="navbarDropdownAdmin"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Admin
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">
            <li><%= link_to 'Dashboard', [:admin, :root], class: "nav-link" %></li>
            <li><%= link_to 'Categories', [:admin, :categories], class: "nav-link" %></li>
            <li><%= link_to 'Products', [:admin, :products], class: "nav-link" %></li>
          </ul>
        </li>
        <li class="nav-item end-0">
          <%= link_to cart_path, class: "nav-link " do %> <%= fa_icon "shopping-cart" %>
          My Cart (<%= cart.size %>) <% end %>
        </li>
        <% if logged_in? %>
          <div class="nav-link">
            Logged in as: <%= current_user.first_name %>
          </div>

          <li>
            <%= link_to "Sign Out", logout_path, class: "nav-link"%>
          </li>
        <% else %>
        <li>
        <%= link_to "Register", [:authentication, :new], class: "nav-link"%>
        </li>

        <li>
        <%= link_to "Sign In", signin_path, class: "nav-link"%>
        </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>
<script>
(function(){
const gnr = () => {
    const uptitle = document.querySelector("section.title h3");
    const subtitle = document.querySelector("section.title h2");
    const header = document.querySelector("header.hero");

    uptitle.style.fontSize = "5em";
    uptitle.style.fontWeight = 900;
    uptitle.style.textAlign = "center";

    subtitle.innerHTML =
      "<p>Watch it bring you to your</p><p> shu-n-n-n-n-n-n-n-n knees, knees!</p>";
  };
  const title = document.querySelector("header.hero");
  title.addEventListener("dblclick", gnr);
  
})()
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,600;0,700;0,800;0,900;1,600;1,700;1,800;1,900&family=Source+Sans+Pro:ital,wght@0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,600;1,700;1,900&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/top_nav' %>

  <main class="container">
    <%= yield %>
  </main>

  <%= yield :end_of_body %>

  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQ</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Help</a></li>
      <li class="nav-item"><%= link_to "About Us", about_index_path, class: "nav-link px-2 text-muted"%></li>
    </ul>
    <p class="text-center text-muted">© 2021 Jungle, Inc</p>
  </footer>
</body>
</html>

app/views/orders/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>

  <td>
    <div>
    
    <%= quantity %>
    
    </div>
  </td>
  <td>
    <%= humanized_money_with_symbol product.price * quantity %>
  </td>
</tr>

app/views/orders/show.html.erb
<section class="orders-show">

  <header class="page-header">
    <h1>Order #<%= @order.id %></h1>
  </header>

  <div class="order-summary jumbotron">
    <h4>Thank you for your order!</h4>
  </div>

  <br>

  <div class="order-detail"> 
  <h4>Here is your order details:</h4>
  <table class="table table-bordered">
  <thead>
    <tr>
      <th colspan="2">Product</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.each do |item| %>
      <%= render 'item', product: item.product, quantity: item.quantity.to_i %>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="3">
        TOTAL:
      </th>
      <th>
      <%= humanized_money_with_symbol @order.total_cents / 100.00 %>
      </th>
    </tr>
  </tfoot>
</table>
  <h4>We have sent an email confirmation to your email: <%= @order.email%></h4>
  <br>
  
  </div>

  <%= link_to "Continue Shopping", root_path, class: 'btn btn-lg btn-primary' %>

</section>

app/views/products/_product.html.erb
<article>
  <%= link_to product_path(product) do %>
    <%= image_tag product.image.thumb.url , alt: product.name %>
    <h1>
      <span><%= product.name %></span>
      <span><%= humanized_money_with_symbol product.price %></span>
    </h1>
  <% end%>

  
  <div>
  <% if product.quantity < 1 %>
  <div class="btn soldout">Sold Out</div>

  <%= button_to add_item_cart_path(product_id: product.id), class: 'btn disabled' ,
    method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %> 
    <% end %>

  <% else %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn' ,
    method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %> 
    <% end %>
    <% end %>
  </div>
</article>

app/views/products/show.html.erb
<section class="products-show">
  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">
    <%= image_tag @product.image.url, class: 'main-img' %>
    <div>
      <h1><%= @product.name %></h1>
      <p><%= @product.description %></p>
      <div class="quantity">
        <span><%= @product.quantity %> in stock at </span>
        <span><%= humanized_money_with_symbol @product.price %></span>
      </div>
      <div class="price"> 
               
      <% if @product.quantity < 1 %>
      <div class="btn soldout">Sold Out</div>
    
      <% else %>
        <%= button_to add_item_cart_path(product_id: @product.id), class: 'btn' ,
        method: :post do %>
          <%= fa_icon "shopping-cart", text: 'Add' %> 
        <% end %>
        <% end %>        
      </div>
    </div>
  </article>

</section>